{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sharp-edge.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
    component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
{{- end }}
