{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    external-dns.alpha.kubernetes.io/target: "8.44.158.127"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.frontend.fqdn }}
      secretName: {{ .Values.app.name }}-tls
  rules:
    - host: {{ .Values.frontend.fqdn }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.app.name }}-backend
                port:
                  number: {{ .Values.backend.port }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.app.name }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
          {{- end }}
{{- end }}
