{{- if and .Values.ingress.enabled .Values.backend.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.app.name }}-strip-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sharp-edge.labels" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: ^/api/?(.*)
    replacement: /$1
{{- end }}
